on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Google Auth
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_PROJECT_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup GCloud
        id: "gcloud-setup"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: GCloud Docker Auth
        run: gcloud auth configure-docker

      - name: Build & Publish Container
        id: "docker-build"
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/www:${{github.sha}} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/www:${{github.sha}}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: www
          image: gcr.io/${{ secrets.GCP_PROJECT }}/www:${{github.sha}}
          region: us-central1

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
